services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: privacy-21
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    image: p21-desafio-app
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env.docker

volumes:
  database:
